filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

filebeat.inputs:
  - type: log
    paths:
      - "/tmp/logs/laravel-*.log"

output.logstash:
  hosts: [ logstash:5000 ]