version: "3.1"
services:
  crud-nginx:
    image: nginx
    container_name: crud-nginx
    volumes:
      - ../:/var/www/html:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_PORT}:80"
    networks:
      - crud

  crud-php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    container_name: crud-php-fpm
    volumes:
      - ../:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - crud

  # Redis
  crud-redis:
    image: redis:alpine
    container_name: crud-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - crud

### elk 설치시 사용가능
### https://github.com/brich-dev-member/b-elk-stack
#  crud-filebeat:
#      image: docker.elastic.co/beats/filebeat:7.14.0
#      container_name: crud-filebeat
#      depends_on:
#        - crud-php-fpm
#      user: root # root 계정 필요
#      volumes:
#        # Filebeat 설정 파일
#        - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
#        # for accessing docker
#        - /var/run/docker.sock:/var/run/docker.sock
#        # log path
#        - type: bind
#          source: ../storage/logs
#          target: /tmp/logs
#          read_only: true
#      networks:
#        - b-elk-stack_elk


# Docker Networks
networks:
  crud:
    driver: bridge
#  b-elk-stack_elk:
#    external: true