version: "3.1"
services:
  menu-talk-nginx:
    image: nginx
    container_name: menu-talk-nginx
    volumes:
      - ../:/var/www/html:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "10040:80"
    networks:
      - menu-talk

  menu-talk-php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menu-talk-php-fpm
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - menu-talk

  mysql:
    image: mysql:latest
    container_name: menu-talk-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: menu_talk
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - menu-talk
    command: --bind-address=0.0.0.0
# Docker Networks
volumes:
  mysql-data:
    driver: local  # 로컬 볼륨 사용
networks:
  menu-talk:
    driver: bridge
#  b-elk-stack_elk:
#    external: true